# Generated by Django 4.1.7 on 2023-05-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', 'Waiting'), ('1', 'On hold'), ('2', 'Working on it'), ('3', 'Done')], default='waiting', max_length=15),
        ),
    ]
